
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR'
export const SIGN_IN_CANCELLED = 'SIGN_IN_CANCELLED'

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR'

export const LOAD_ASYNCSTORAGE = 'LOAD_ASYNCSTORAGE'

export const LOAD_USER_DATA_SUCCESS = 'LOAD_USER_DATA_SUCCESS'
export const LOAD_USER_DATA_ERROR = 'LOAD_USER_DATA_'

export const LOAD_SECTION_DATA_SUCCESS = 'LOAD_SECTION_DATA_SUCCESS'
export const LOAD_SECTION_DATA_ERROR = 'LOAD_SECTION_DATA_ERROR'

export const BOTTOM_SHEET_STATUS= 'BOTTOM_SHEET_STATUS'

